project:
  type: website

website:
  title: "SDS Summit 2026 Reimbursement"
  navbar:
    left:
      - href: index.qmd
        text: General Process
      - href: registration-us.qmd
        text: US Individual
      - href: registration-foreign.qmd
        text: International Individual
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



