project:
  type: website
  output-dir: _site


website:
  title: "SDS Summit 2026 Reimbursement"
  site-url: https://jinhuang0205.github.io
  site-path: /sdss26-reimbursement/

  navbar:
    left:
      - href: index.qmd
        text: General Process
      - href: registration-us.qmd
        text: US Individual
      - href: registration-foreign.qmd
        text: International Individual
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



